name: Tests and release
on:
  push:
    branches:
      - master
      - beta
      - theming-v2
  pull_request:
    branches:
      - master
      - beta
      - theming-v2
jobs:
  workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build:prod
      - name: Linting
        run: |
          npm run lint
      - name: Unit tests
        run: |
          npm run test:ci
      # Turned off until we have a (pre)release for theming-v2
      # - name: E2e tests
      #   env:
      #     STREAM_API_KEY: ${{ secrets.API_KEY }}
      #     STREAM_USER_ID: ${{ secrets.USER_ID }}
      #     STREAM_USER_TOKEN: ${{ secrets.USER_TOKEN }}
      #   run: |
      #     npm run e2e:ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Pull stream-chat-css
        uses: actions/checkout@v3
        with:
          repository: GetStream/stream-chat-css
          path: stream-chat-css
          ref: ${{ node -e 'pkg=require("./package.json"); console.log(pkg.dependencies["@stream-io/stream-chat-css"])' }}
      - name: Copy docs from stream-chat-css
        env:
          DOCS_SOURCE: stream-chat-css/docs
        run: npm run copy-css-docs
      - name: Generate docs
        run: |
          npm run generate-docs
      - name: Push to docusaurus
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
